spring.application.name=youChat

# Server Config
server.port=8080

# Ollama Config
ollama.url=${OLLAMA_URL:http://localhost:11434}
ollama.model=${OLLAMA_MODEL:qwen2.5:14b}

# PostgreSQL connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAE}
spring.datasource.password=${DB_PASSWORD}

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
